# Generated by Django 5.0.7 on 2024-08-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_organization_name_userprofile_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organizations',
        ),
    ]
