# Generated by Django 5.0.7 on 2024-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.organization'),
        ),
    ]
