# Generated by Django 5.0.7 on 2024-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Default Organization Name', max_length=150, verbose_name='nome'),
        ),
    ]
