# Generated by Django 5.0.7 on 2024-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Organization Name', max_length=150, verbose_name='nome'),
        ),
    ]
