# Generated by Django 5.0.7 on 2024-08-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type_permission',
            field=models.CharField(choices=[('owner', 'Proprietario'), ('admin', 'Administrador'), ('user', 'Usuario')], default='admin', max_length=10),
        ),
    ]
