# Generated by Django 5.0.7 on 2024-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_membership_type_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type_permission',
            field=models.CharField(choices=[('owner', 'Proprietario'), ('admin', 'Administrador'), ('user', 'Colaborador')], default='admin', max_length=10),
        ),
    ]
