# Generated by Django 5.0.7 on 2024-08-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_membership_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
    ]
