# Generated by Django 5.0.7 on 2024-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_membership_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(through='users.Membership', to='users.organization'),
        ),
    ]
