# Generated by Django 5.0.7 on 2024-08-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('work', 'Trabalho'), ('guys', 'Pessoal'), ('studies', 'Estudos'), ('other', 'Outras')], default='other', max_length=10, verbose_name='Tipo de Categoria'),
        ),
    ]
