# Generated by Django 5.0.7 on 2024-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('work', 'Trabalho'), ('particular', 'Particular'), ('studies', 'Estudos'), ('other', 'Outras')], default='other', max_length=10, verbose_name='Tipo de Categoria'),
        ),
    ]
