# Generated by Django 5.0.7 on 2024-08-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_category_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='organization',
        ),
    ]
