# Generated by Django 5.0.7 on 2024-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_category_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=150, verbose_name='Conteúdo'),
        ),
    ]
