# Generated by Django 5.0.7 on 2024-08-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_room_messages_remove_room_user_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
